### PR TITLE
update: single string translation support added for Shipping Status, RMA Reason, Abuse Report Reason

### PR DESCRIPTION
**Pull request by shohag121**
Single string translation and retrieval support added
```php

   /**
     * Register single string.
     *
     * @since 1.0.11
     *
     * @param string $context This value gives the string you are about to register a context.
     * @param string $name The name of the string that helps the translator understand what’s being translated.
     * @param string $value The string that needs to be translated.
     *
     * @return void
     */
    public function register_single_string( $context, $name, $value ) {
        do_action( 'wpml_register_single_string', $context, $name, $value );
    }

    /**
     * Get translated single string.
     *
     * @since 1.0.11
     *
     * @param string $original_value The string’s original value.
     * @param string $domain The string’s registered domain.
     * @param string $name The string’s registered name.
     * @param $language_code
     *
     * @return string
     */
    public function get_translated_single_string( $original_value, $domain, $name, $language_code = null ) {
        return apply_filters( 'wpml_translate_single_string', $original_value, $domain, $name, $language_code );
    }
```

Single string translation for Shipping Status, Abuse report, and RMA Reason Added.

```php
       // Single string translation.
        add_action( 'dokan_pro_register_shipping_status', [ $this, 'register_shipping_status_single_string' ] );
        add_action( 'dokan_pro_register_abuse_report_reason', [ $this, 'register_abuse_report_single_string' ] );
        add_action( 'dokan_pro_register_rms_reason', [ $this, 'register_rma_single_string' ] );
        add_filter( 'dokan_pro_shipping_status', [ $this, 'get_translated_shipping_status' ] );
        add_filter( 'dokan_pro_abuse_report_reason', [ $this, 'get_translated_abuse_report_reason' ] );
        add_filter( 'dokan_pro_rma_reason', [ $this, 'get_translated_rma_reason' ] );
        
        
    /**
     * Register shipping status single string.
     *
     * @since 1.0.11
     *
     * @param string $status Shipping Status.
     *
     * @return void
     */
    public function register_shipping_status_single_string( $status ) {
        $this->register_single_string( 'dokan', 'Dokan Shipping Status: ' . $status, $status );
    }

    /**
     * Register abuse report single string.
     *
     * @since 1.0.11
     *
     * @param string $reason Abuse report reason.
     *
     * @return void
     */
    public function register_abuse_report_single_string( $reason ) {
        $this->register_single_string( 'dokan', 'Dokan Abuse Reason: ' . $reason, $reason );
    }

    /**
     * Register RMA reason single string.
     *
     * @since 1.0.11
     *
     * @param string $reason RMA reason.
     *
     * @return void
     */
    public function register_rma_single_string( $reason ) {
        $this->register_single_string( 'dokan', 'Dokan Refund and Returns Reason: ' . $reason, $reason );
    }

    /**
     * Get translated shipping status.
     *
     * @since 1.0.11
     *
     * @param string $status Shipping Status.
     *
     * @return string
     */
    public function get_translated_shipping_status( $status ) {
        return $this->get_translated_single_string( $status, 'dokan', 'Dokan Shipping Status: ' . $status );
    }

    /**
     * Get translated abuse report reason.
     *
     * @since 1.0.11
     *
     * @param string $reason Abuse report reason.
     *
     * @return string
     */
    public function get_translated_abuse_report_reason( $reason ) {
        return $this->get_translated_single_string( $reason, 'dokan', 'Dokan Abuse Reason: ' . $reason );
    }

    /**
     * Get translated RMA reason.
     *
     * @since 1.0.11
     *
     * @param string $reason RMA reason.
     *
     * @return string
     */
    public function get_translated_rma_reason( $reason ) {
        return $this->get_translated_single_string( $reason, 'dokan', 'Dokan Refund and Returns Reason: ' . $reason );
    }
```

### CODE REVIEW

**Review by nurul-umbhiya — APPROVED** [review]

**Comment by Sophie-2e** [comment]
Hey @shohag121 @nurul-umbhiya , just updated Dokan WPML to v1.1.0 and tested but the RMA reasons are still only shown translated at 50% even though they are translated in WPML: https://ibb.co/qyY2QwK

**Comment by nurul-umbhiya** [comment]
@Sophie-2e kindly create a support ticket for this with staging site details. We will take care of this.

**Comment by Sophie-2e** [comment]
Hello @nurul-umbhiya, support tickets are all created since a while and they have the credentials already:
- Shipping Statut: #41682 — WPML - SELLER DASHBOARD - STORE SETTINGS > SHIPPING : many fields cannot be translatable: I am waiting for news from Sazzat
- RMA reasons: #41624 — WPML - CUSTOMER ACCOUNT - RETURN & REFUND > All RMA reasons translated but only 50% shown in front end: also hangled by Sazzat
- Abuse Report Reason: #41104 — WPML - PRODUCT ABUSE REPORT ON PRODUCT PAGE - Dokan "Product Abuse Report" REASONS cannot be translated in WPML and shown in english the front end + #41093 — WPML - PRODUCT ABUSE REPORT - Dokan "Product Abuse Report" LABEL translated in WPML but not shown in front end: Also waiting for news from Sazzat here

According to Sazzat, your developers are working on it, but seems you do not have access to the staging website, so what is the real status of these issues? Please let me know, thank you.

**Comment by Sophie-2e** [comment]
Hello @nurul-umbhiya 

Update: the Abuse Report Reason has been fixed actually with the last Dokan WPML released.

 But these ones still not:
- Shipping Statut: #41682 — WPML - SELLER DASHBOARD - STORE SETTINGS > SHIPPING : many fields cannot be translatable: I am waiting for news from Sazzat
- RMA reasons: #41624 — WPML - CUSTOMER ACCOUNT - RETURN & REFUND > All RMA reasons translated but only 50% shown in front end: also handled by Sazzat

**Comment by Sophie-2e** [comment]
@nurul-umbhiya @shohag121  Any update on this?

**Comment by shohag121** [comment]
Hello @Sophie-2e,

Did you try translating from WPML String translation?
If yes and still they are not showing up on the front end then please proceed with the following steps below.
- Visit WP Admin -> Dokan -> Settings
- Click On `SHIPPING STATUS` Tab and click on save
- Click On `RMA` Tab and click on save
- Click On `PRODUCT REPORT ABUSE` Tab and click on save
- Visit String Translation Settings Page
- Search with `Dokan Shipping Status:` and translate the results
- Search with `Dokan Abuse Reason:` and translate the results
- Search with `Dokan Refund and Returns Reason:` and translate the results

Check the front end again, this time the status will be translated.

If this does not help please let me know.

Thank You.

**Comment by Sophie-2e** [comment]
Hello @shohag121 , indeed sorry, I reviewed my note and RMA and Product Report Reasons are fixed, I could also fix the Shipping Status by following your guidelines, thanks a lot for the tips. The issues remaining with shipping is: https://github.com/getdokan/dokan-wpml/issues/35

And then there are all the issues I opened recently in the WPML repository after updating Dokan Lite and Pro to 3.10.2 : https://github.com/getdokan/dokan-wpml/issues Please review the list in order to see all the one related to shipping and prioritise the one with ⚠️⚠️⚠️

Thanks a lot for your help :)

**Pull request merged**
